from typing import TypedDict, List, Optional, Literal, Any, Dict

# --- Subgraph State ---
class SpgState(TypedDict):
    # --- Input (from upstream) ---
    task_description: str       # Description of the upgrade task
    target_files: List[str]     # List of files to modify
    
    # --- Internal Context ---
    retrieved_patterns: str     # RAG retrieved patterns
    
    # --- Artifacts ---
    cocci_script: str           # Current .cocci script
    mock_c_code: str            # Mock C code for dry run
    
    # --- Feedback Loop ---
    validation_error: Optional[str] # Error from spatch or Logic error
    patch_preview: Optional[str]    # Patch generated by dry run
    iteration_count: int        # Loop counter
    
    # --- Output (to downstream) ---
    final_cocci_script: Optional[str]
    applied_diff: Optional[str]
    status: Literal["processing", "success", "failed"]

# --- Main Graph State ---
class AgentState(TypedDict):
    user_request: str          # User's natural language request or git diff
    
    # Feasibility Analysis
    feasibility_result: Optional[Dict[str, Any]] # JSON output from analysis
    strategy: Optional[Literal["COCCI", "LLM_DIRECT"]] # Strategy decision
    
    # Coccinelle Flow
    spg_output: Optional[Dict[str, Any]] # Result from SpgState
    
    # LLM Direct Flow
    llm_refactor_result: Optional[str] # Result from LLM direct applied changes
    
    # Common
    final_diff: Optional[str]  # Final applied diff for review
    review_comments: Optional[str] # Comments from reviewer

